// AutolinkedNativeModules.g.cs contents generated by "react-native autolink-windows"

using System.Collections.Generic;

// Namespaces from react-native-camera
using ReactNativeCameraCPP;

// Namespaces from react-native-windows-uwp-camera
using ReactNativeWindowsUwpCamera;

namespace Microsoft.ReactNative.Managed
{
    internal static class AutolinkedNativeModules
    {
        internal static void RegisterAutolinkedNativeModulePackages(IList<IReactPackageProvider> packageProviders)
        { 
            // IReactPackageProviders from react-native-camera
            packageProviders.Add(new ReactNativeCameraCPP.ReactPackageProvider());
            // IReactPackageProviders from react-native-windows-uwp-camera
            packageProviders.Add(new ReactNativeWindowsUwpCamera.ReactPackageProvider());
        }
    }
}
